spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ledger
    username: postgres
    password: devpassword123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    org.springframework.web: DEBUG